language: ruby
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
    - libtinfo-dev 
    - exonerate  
    - blast2
    - ncbi-blast+
    - mafft
    - primer3
before_install:
  - gem update --system
  - export RUBYOPT="-W1"
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7


